### ISSUE TITLE
homework review completed, 請調整

### ISSUE THREAD

**Issue by hatelove** [linalex1314/TDD_HW1#1]
需要調整下列事項：

1. 我並沒有在測試案例中看到那 11 筆資料，這會導致閱讀測試案例的人無法知道，為什麼傳入3與Cost時，會得到{ 6, 15, 24, 21 }的結果。

**Comment by hatelove** [comment]
另外，使用 github 的方式，可以參考這篇文章：https://dotblogs.com.tw/hatelove/2016/04/11/how-to-connect-github-repo-with-visual-studio-2015

**Comment by linalex1314** [comment]
謝謝文章,很實用,
Code調整完成

**Comment by hatelove** [comment]
Review completed.

這邊也提供我的 sample solution 給您參考一下：http://bit.ly/91-tdd-day1-homework-solution
第一版只支援 Product, 第二版則使用 extension method + generic + lambda 來支援任意型別。

您也可以參考一下，初始化11筆Product資料的方式，我不建議用 .Add() 來加，因為語意比較不直覺，而且要多打比較多的字。
